networks:
  vcard-network:
    name: vcard-network
    external: true

services:
  backend-vcard:
    container_name: backend-vcard
    image: backend-vcard
    build: .
    networks:
      - vcard-network
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ISSUER_URI: ${ISSUER_URI}
      LAMBDA_USERNAME: ${LAMBDA_USERNAME}
      LAMBDA_PASSWORD: ${LAMBDA_PASSWORD}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - 8080:8080
    restart: on-failure